### ISSUE TITLE
trying to run, getting blank command screen

### ISSUE THREAD

**Issue by AWanderingMage** [cemasma/water-sort-puzzle-solver#2]
So ive cloned the repo, ran the go build . command and have a .exe in the file now, but im not sure how to run the json file ive created with the puzzle im trying to solve. any ideas?

**Comment by cemasma** [comment]
Hey @AWanderingMage, you can run the executable using your command prompt like this.
`
.\water-sort-puzzle-solver.exe --file 139.json
`
Do not forget to navigate your command prompt to the directory that contains the executable before trying.

**Comment by HRichbourg** [comment]
This is giving the command not found error for me: zsh: command not found: .water-sort-puzzle-solver.exe . I am in the correct folder with the .exe file and was able to correctly build without any errors. I also made the file executable (chmod +x). Any other ideas? Thanks
