### ISSUE TITLE
Is the question unanswerable?

### ISSUE THREAD

**Issue by zangputi** [cemasma/water-sort-puzzle-solver#3]
I have a question here. I entered it into the program and ran it for five or six hours, and it still cannot provide an answer.
{
  "bottles": [
    [
      "1",
      "3",
      "2",
      "1"
    ],
    [
      "7",
      "6",
      "5",
      "4"
    ],
    [
      "8",
      "10",
      "7",
      "9"
    ],
    [
      "9",
      "4",
      "7",
      "10"
    ],
    [
      "4",
      "2",
      "6",
      "1"
    ],
    [
      "5",
      "3",
      "2",
      "9"
    ],
    [
      "3",
      "2",
      "6",
      "4"
    ],
    [
      "9",
      "6",
      "8",
      "10"
    ],
    [
      "1",
      "8",
      "5",
      "8"
    ],
    [
      "3",
      "10",
      "5",
      "7"
    ],
    [
      "EMPTY",
      "EMPTY",
      "EMPTY",
      "EMPTY"
    ],
    [
      "EMPTY",
      "EMPTY",
      "EMPTY",
      "EMPTY"
    ]
  ]
}

**Comment by cemasma** [comment]
How did you run it for hours? It is responding with empty solution array in 7 seconds for me and yes it seems that input has no answer, it is getting locked for the every variant of moves.
